connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password: tarnawski

development:
  <<: *connection
  database: nti

test: &test
  <<: *connection
  database: nti


testowa:
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password: tarnawski
  database: test
